import { createContext, useContext, useMemo, type ReactNode } from "react";
import { useAuth } from "./AuthContext";
import { apiFetch } from "../lib/apiClient";
import type { AuthUser } from "../lib/types";

export type Language = "pt" | "en";

export type UserProfile = {
  name: string;
  email: string;
  avatarUrl: string;
  language: Language;
  theme: "light" | "dark";
  sidebarVisible: boolean;
};

type UserContextType = {
  profile: UserProfile;
  updateProfile: (updates: Partial<UserProfile>) => Promise<void>;
};

const defaultProfile: UserProfile = {
  name: "Usuário",
  email: "",
  avatarUrl: "",
  language: "pt",
  theme: "light",
  sidebarVisible: true,
};

const UserContext = createContext<UserContextType>({
  profile: defaultProfile,
  updateProfile: async () => {},
});

export function useUser() {
  return useContext(UserContext);
}

function toProfile(user: AuthUser | null): UserProfile {
  if (!user) return defaultProfile;
  return {
    name: user.name || defaultProfile.name,
    email: user.email || "",
    avatarUrl: user.avatarUrl ?? "",
    language: user.language === "en" ? "en" : "pt",
    theme: user.theme === "dark" ? "dark" : "light",
    sidebarVisible: user.sidebarVisible !== false,
  };
}

export function UserProvider({ children }: { children: ReactNode }) {
  const { user, setAuthenticatedUser } = useAuth();
  const profile = useMemo(() => toProfile(user), [user]);

  async function updateProfile(updates: Partial<UserProfile>) {
    if (!user) return;

    const payload = {
      name: updates.name,
      avatarUrl: updates.avatarUrl,
      language: updates.language,
      theme: updates.theme,
      sidebarVisible: updates.sidebarVisible,
    };

    const nextUser = await apiFetch<AuthUser>("/auth/me", {
      method: "PATCH",
      body: JSON.stringify(payload),
    });

    setAuthenticatedUser(nextUser);
  }

  return (
    <UserContext.Provider value={{ profile, updateProfile }}>
      {children}
    </UserContext.Provider>
  );
}

// ─── Translations ────────────────────────────────────────────────────────────

export const translations = {
  pt: {
    dashboard: "Dashboard",
    applications: "Candidaturas",
    statistics: "Estatísticas",
    settings: "Configurações",
    search_placeholder: "Buscar candidaturas...",
    search_navigate_hint: "Pressione Enter para buscar",
    profile: "Perfil",
    appearance: "Aparência",
    language: "Idioma",
    theme_light: "Claro",
    theme_dark: "Escuro",
    name: "Nome",
    avatar_url: "URL da foto de perfil",
    save: "Salvar",
    saved: "Salvo!",
    notifications: "Notificações",
    notifications_due_title: "Follow-ups atrasados",
    notifications_due_empty: "Nenhum follow-up atrasado agora.",
    notifications_due_banner: (count: number) => `${count} follow-up${count > 1 ? "s" : ""} atrasado${count > 1 ? "s" : ""}`,
    notifications_due_today: "Vence hoje",
    notifications_due_overdue: "Atrasado",
    notifications_due_on: (date: string) => `Vence em ${date}`,
    open_menu: "Abrir menu",
    clear_search: "Limpar busca",
    close: "Fechar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Deletar",
    previous: "Anterior",
    next: "Próximo",
    status: "Status",
    priority: "Prioridade",
    priority_low: "Baixa",
    priority_medium: "Média",
    priority_high: "Alta",
    applied_date: "Data de aplicação",
    follow_up_date: "Data de follow-up",
    follow_up_help: "Data para lembrar de acompanhar esta candidatura.",
    company_required: "Empresa *",
    role_required: "Cargo/Vaga *",
    error: "Erro",
    error_loading: "Erro ao carregar",
    profile_menu: "Perfil",
    show_sidebar: "Mostrar menu lateral",
    hide_sidebar: "Esconder menu lateral",
    logout: "Sair",
    auth_login_title: "Entrar",
    auth_login_subtitle: "Acesse sua conta para continuar.",
    auth_register_title: "Criar conta",
    auth_register_subtitle: "Comece a acompanhar suas candidaturas.",
    auth_name_placeholder: "Seu nome",
    auth_email: "E-mail",
    auth_password: "Senha",
    auth_login_button: "Entrar",
    auth_register_button: "Criar conta",
    auth_login_loading: "Entrando...",
    auth_register_loading: "Criando conta...",
    auth_no_account: "Ainda não tem conta?",
    auth_have_account: "Já tem conta?",
    auth_switch_to_register: "Criar agora",
    auth_switch_to_login: "Entrar",
    auth_generic_error: "Não foi possível autenticar.",
    status_applied: "Aplicada",
    status_interview: "Entrevista",
    status_offer: "Oferta",
    status_rejected: "Rejeitada",
    // Dashboard
    total: "Total",
    applied: "Aplicadas",
    interview: "Entrevistas",
    offers: "Ofertas",
    rejected: "Rejeitadas",
    overview: "Visão geral das suas candidaturas",
    metrics: "Métricas",
    interview_rate: "Taxa de entrevista",
    offer_rate: "Taxa de oferta",
    see_all: "Ver todas →",
    see_stats: "Ver estatísticas completas →",
    new_application: "Nova Candidatura",
    recent_applications: "Candidaturas recentes",
    dashboard_followups_title: "Follow-ups pendentes",
    dashboard_followups_empty: "Nenhum follow-up pendente hoje.",
    no_applications_yet: "Nenhuma candidatura ainda.",
    start_now: "Comece agora!",
    add_first_desc: "Adicione sua primeira candidatura para começar a acompanhar.",
    add_application: "Adicionar candidatura",
    loading: "Carregando...",
    registered: "candidaturas registradas",
    of: "de",
    applications_count: (n: number) => `${n} candidatura${n !== 1 ? "s" : ""} registradas`,
    // Statistics
    status_distribution: "Distribuição por status",
    conversion_funnel: "Funil de conversão",
    conversion_rates: "Taxas de conversão",
    monthly_chart: "Candidaturas por mês",
    statistics_simple_title: "Resumo simples",
    statistics_simple_desc: "Leitura rápida para entender seu progresso sem termos técnicos.",
    statistics_out_of_ten: "A cada 10 candidaturas:",
    statistics_ten_interviews: "Chegam em entrevista",
    statistics_ten_offers: "Viram oferta",
    statistics_ten_rejected: "São rejeitadas",
    statistics_tip_title: "Dica rápida",
    statistics_tip_interview: "Tente ajustar currículo e palavras-chave das vagas para aumentar entrevistas.",
    statistics_tip_offer: "Você já entrevista bem. Foque em preparação para etapa final e negociação.",
    statistics_tip_keep: "Ótimo ritmo! Continue no que está funcionando e mantenha consistência.",
    status_distribution_desc: "Mostra em que etapa suas candidaturas estão neste momento.",
    conversion_funnel_desc: "Quantidade que avança em cada fase.",
    conversion_rates_desc: "Percentuais de avanço entre etapas.",
    monthly_chart_desc: "Volume de candidaturas enviadas por mês.",
    monthly_best_month: (month: string, count: number) => `Melhor mês: ${month} (${count})`,
    monthly_average: (avg: number) => `Média por mês: ${avg.toFixed(1)}`,
    no_data_title: "Sem dados ainda",
    no_data_desc: "Adicione candidaturas para ver as estatísticas aqui.",
    total_applications: (n: number) => `${n} candidaturas no total`,
    reached_interview: "Chegaram a entrevista",
    received_offer: "Receberam oferta",
    all_applications: "Total candidatas",
    app_to_interview: "Aplicação → Entrevista",
    interview_to_offer: "Entrevista → Oferta",
    app_to_offer: "Aplicação → Oferta (geral)",
    of_interviews: "entrevistas",
    of_applications: "candidaturas",
    // Applications page
    applications_title: "Minhas Candidaturas",
    applications_registered: (n: number) => `${n} candidaturas registradas`,
    applications_filter_all: "Todas",
    applications_sort_by: "Ordenar por:",
    applications_sort_date_desc: "Data (mais recente)",
    applications_sort_date_asc: "Data (mais antiga)",
    applications_sort_company_asc: "Empresa (A-Z)",
    applications_sort_priority_desc: "Prioridade (alta primeiro)",
    applications_sort_follow_up_asc: "Follow-up (mais próximo)",
    applications_followup_due_only: "Follow-up pendente",
    applications_followup_overdue_only: "Follow-up atrasado",
    applications_search_placeholder: "Buscar por empresa ou vaga...",
    applications_page_of: (page: number, totalPages: number) => `Página ${page} de ${totalPages}`,
    applications_empty_title: "Nenhuma candidatura ainda",
    applications_empty_desc: "Adicione sua primeira candidatura para começar a acompanhar.",
    applications_add_first: "Adicionar primeira candidatura",
    applications_not_found_title: "Nada encontrado",
    applications_not_found_desc: "Tente buscar por outro termo (empresa ou vaga).",
    applications_no_match_filters: "Nenhuma candidatura corresponde aos filtros atuais.",
    applications_clear_filters: "Limpar filtros",
    applications_applied_on: "Aplicado em:",
    applications_change_status: "Mudar status",
    applications_export_csv: "Exportar CSV",
    applications_import_csv: "Importar CSV",
    applications_export_json: "Backup JSON",
    applications_import_json: "Restaurar JSON",
    applications_exporting: "Exportando...",
    applications_importing: "Importando...",
    applications_export_empty: "Nenhuma candidatura para exportar.",
    applications_export_success: (count: number) => `${count} candidaturas exportadas.`,
    applications_export_json_success: (count: number) => `${count} candidaturas no backup JSON.`,
    applications_import_success: (created: number, skipped: number) =>
      `${created} importadas${skipped > 0 ? `, ${skipped} ignoradas` : ""}.`,
    applications_import_error: "Erro ao importar CSV.",
    applications_import_file_invalid: "Arquivo CSV inválido ou sem dados.",
    applications_import_json_success: (created: number, skipped: number) =>
      `${created} restauradas${skipped > 0 ? `, ${skipped} ignoradas` : ""}.`,
    applications_import_json_error: "Erro ao restaurar JSON.",
    applications_import_json_invalid: "Arquivo JSON inválido ou sem dados.",
    applications_view_grid: "Cards",
    applications_view_kanban: "Kanban",
    applications_kanban_empty: "Arraste cards para este status.",
    applications_history: "Histórico",
    applications_history_title: "Histórico de status",
    applications_history_loading: "Carregando histórico...",
    applications_history_empty: "Ainda não há mudanças de status registradas.",
    applications_history_initial: "Status inicial",
    applications_history_error: "Erro ao carregar histórico.",
    applications_followup_due_today: "Follow-up vence hoje",
    applications_followup_overdue: "Follow-up atrasado",
    applications_followup_due_on: (date: string) => `Follow-up em ${date}`,
    applications_change_status_title: "Mudar status",
    applications_edit_title: "Editar candidatura",
    applications_delete_title: "Deletar candidatura",
    applications_delete_confirm: (company: string, role: string) =>
      `Tem certeza que deseja deletar a candidatura de ${company} para ${role}?`,
    applications_busy_updating: "Atualizando...",
    applications_busy_saving: "Salvando...",
    applications_busy_deleting: "Deletando...",
    applications_created_title: "Candidatura criada!",
    applications_created_msg: "Salva com sucesso.",
    applications_updated_title: "Atualizada!",
    applications_updated_msg: "Candidatura editada com sucesso.",
    applications_deleted_title: "Removida!",
    applications_deleted_msg: "Candidatura deletada.",
    applications_status_updated_title: "Status atualizado!",
    applications_status_updated_msg: (status: string) => `Agora está como ${status}.`,
    applications_error_fetch: "Erro ao buscar candidaturas",
    applications_error_create: "Erro ao criar",
    applications_error_edit: "Erro ao editar",
    applications_error_update_status: "Erro ao atualizar status",
    applications_error_delete: "Erro ao deletar",
    applications_error_retry: "Tente novamente.",
    applications_error_api_hint:
      "Confere se a API está rodando em localhost:8080 e se o CORS está liberado para localhost:5173.",
    // Campos novos (Sprint 2)
    notes: "Observações",
    notes_placeholder: "Notas, próximos passos, contatos...",
    job_url: "Link da vaga",
    job_url_placeholder: "https://linkedin.com/jobs/...",
    salary: "Salário / Faixa",
    salary_placeholder: "Ex: R$ 5.000–8.000",
    open_job_link: "Abrir vaga",
  },
  en: {
    dashboard: "Dashboard",
    applications: "Applications",
    statistics: "Statistics",
    settings: "Settings",
    search_placeholder: "Search applications...",
    search_navigate_hint: "Press Enter to search",
    profile: "Profile",
    appearance: "Appearance",
    language: "Language",
    theme_light: "Light",
    theme_dark: "Dark",
    name: "Name",
    avatar_url: "Profile photo URL",
    save: "Save",
    saved: "Saved!",
    notifications: "Notifications",
    notifications_due_title: "Overdue follow-ups",
    notifications_due_empty: "No overdue follow-ups right now.",
    notifications_due_banner: (count: number) => `${count} overdue follow-up${count !== 1 ? "s" : ""}`,
    notifications_due_today: "Due today",
    notifications_due_overdue: "Overdue",
    notifications_due_on: (date: string) => `Due on ${date}`,
    open_menu: "Open menu",
    clear_search: "Clear search",
    close: "Close",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    previous: "Previous",
    next: "Next",
    status: "Status",
    priority: "Priority",
    priority_low: "Low",
    priority_medium: "Medium",
    priority_high: "High",
    applied_date: "Applied date",
    follow_up_date: "Follow-up date",
    follow_up_help: "Date to remind you to follow up on this application.",
    company_required: "Company *",
    role_required: "Role/Position *",
    error: "Error",
    error_loading: "Error loading",
    profile_menu: "Profile",
    show_sidebar: "Show sidebar",
    hide_sidebar: "Hide sidebar",
    logout: "Logout",
    auth_login_title: "Sign in",
    auth_login_subtitle: "Access your account to continue.",
    auth_register_title: "Create account",
    auth_register_subtitle: "Start tracking your job applications.",
    auth_name_placeholder: "Your name",
    auth_email: "Email",
    auth_password: "Password",
    auth_login_button: "Sign in",
    auth_register_button: "Create account",
    auth_login_loading: "Signing in...",
    auth_register_loading: "Creating account...",
    auth_no_account: "Don't have an account yet?",
    auth_have_account: "Already have an account?",
    auth_switch_to_register: "Create one",
    auth_switch_to_login: "Sign in",
    auth_generic_error: "Could not authenticate.",
    status_applied: "Applied",
    status_interview: "Interview",
    status_offer: "Offer",
    status_rejected: "Rejected",
    // Dashboard
    total: "Total",
    applied: "Applied",
    interview: "Interviews",
    offers: "Offers",
    rejected: "Rejected",
    overview: "Overview of your job applications",
    metrics: "Metrics",
    interview_rate: "Interview rate",
    offer_rate: "Offer rate",
    see_all: "See all →",
    see_stats: "See full statistics →",
    new_application: "New Application",
    recent_applications: "Recent applications",
    dashboard_followups_title: "Due follow-ups",
    dashboard_followups_empty: "No follow-up due today.",
    no_applications_yet: "No applications yet.",
    start_now: "Start now!",
    add_first_desc: "Add your first application to start tracking.",
    add_application: "Add application",
    loading: "Loading...",
    registered: "applications registered",
    of: "of",
    applications_count: (n: number) => `${n} application${n !== 1 ? "s" : ""} registered`,
    // Statistics
    status_distribution: "Status distribution",
    conversion_funnel: "Conversion funnel",
    conversion_rates: "Conversion rates",
    monthly_chart: "Applications by month",
    statistics_simple_title: "Simple summary",
    statistics_simple_desc: "Quick view to understand your progress without technical terms.",
    statistics_out_of_ten: "Out of every 10 applications:",
    statistics_ten_interviews: "Reach interviews",
    statistics_ten_offers: "Become offers",
    statistics_ten_rejected: "Are rejected",
    statistics_tip_title: "Quick tip",
    statistics_tip_interview: "Try improving resume keywords and role targeting to increase interviews.",
    statistics_tip_offer: "You are reaching interviews. Focus on final-round preparation and negotiation.",
    statistics_tip_keep: "Great momentum. Keep what is working and stay consistent.",
    status_distribution_desc: "Shows where your applications currently stand.",
    conversion_funnel_desc: "How many move forward at each stage.",
    conversion_rates_desc: "Progress percentages between stages.",
    monthly_chart_desc: "How many applications you sent each month.",
    monthly_best_month: (month: string, count: number) => `Best month: ${month} (${count})`,
    monthly_average: (avg: number) => `Average per month: ${avg.toFixed(1)}`,
    no_data_title: "No data yet",
    no_data_desc: "Add applications to see statistics here.",
    total_applications: (n: number) => `${n} total application${n !== 1 ? "s" : ""}`,
    reached_interview: "Reached interview",
    received_offer: "Received offer",
    all_applications: "Total applied",
    app_to_interview: "Application → Interview",
    interview_to_offer: "Interview → Offer",
    app_to_offer: "Application → Offer (overall)",
    of_interviews: "interviews",
    of_applications: "applications",
    // Applications page
    applications_title: "My Applications",
    applications_registered: (n: number) => `${n} applications registered`,
    applications_filter_all: "All",
    applications_sort_by: "Sort by:",
    applications_sort_date_desc: "Date (newest)",
    applications_sort_date_asc: "Date (oldest)",
    applications_sort_company_asc: "Company (A-Z)",
    applications_sort_priority_desc: "Priority (high first)",
    applications_sort_follow_up_asc: "Follow-up (nearest first)",
    applications_followup_due_only: "Follow-up due",
    applications_followup_overdue_only: "Follow-up overdue",
    applications_search_placeholder: "Search by company or role...",
    applications_page_of: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
    applications_empty_title: "No applications yet",
    applications_empty_desc: "Add your first application to start tracking.",
    applications_add_first: "Add first application",
    applications_not_found_title: "No results found",
    applications_not_found_desc: "Try searching for another term (company or role).",
    applications_no_match_filters: "No applications match the current filters.",
    applications_clear_filters: "Clear filters",
    applications_applied_on: "Applied on:",
    applications_change_status: "Change status",
    applications_export_csv: "Export CSV",
    applications_import_csv: "Import CSV",
    applications_export_json: "Backup JSON",
    applications_import_json: "Restore JSON",
    applications_exporting: "Exporting...",
    applications_importing: "Importing...",
    applications_export_empty: "No applications to export.",
    applications_export_success: (count: number) => `${count} applications exported.`,
    applications_export_json_success: (count: number) => `${count} applications in JSON backup.`,
    applications_import_success: (created: number, skipped: number) =>
      `${created} imported${skipped > 0 ? `, ${skipped} skipped` : ""}.`,
    applications_import_error: "Error importing CSV.",
    applications_import_file_invalid: "Invalid CSV file or no valid rows.",
    applications_import_json_success: (created: number, skipped: number) =>
      `${created} restored${skipped > 0 ? `, ${skipped} skipped` : ""}.`,
    applications_import_json_error: "Error restoring JSON.",
    applications_import_json_invalid: "Invalid JSON file or no valid rows.",
    applications_view_grid: "Cards",
    applications_view_kanban: "Kanban",
    applications_kanban_empty: "Drag cards to this status.",
    applications_history: "History",
    applications_history_title: "Status history",
    applications_history_loading: "Loading history...",
    applications_history_empty: "No status changes recorded yet.",
    applications_history_initial: "Initial status",
    applications_history_error: "Error loading history.",
    applications_followup_due_today: "Follow-up due today",
    applications_followup_overdue: "Follow-up overdue",
    applications_followup_due_on: (date: string) => `Follow-up on ${date}`,
    applications_change_status_title: "Change status",
    applications_edit_title: "Edit application",
    applications_delete_title: "Delete application",
    applications_delete_confirm: (company: string, role: string) =>
      `Are you sure you want to delete the application for ${role} at ${company}?`,
    applications_busy_updating: "Updating...",
    applications_busy_saving: "Saving...",
    applications_busy_deleting: "Deleting...",
    applications_created_title: "Application created!",
    applications_created_msg: "Saved successfully.",
    applications_updated_title: "Updated!",
    applications_updated_msg: "Application updated successfully.",
    applications_deleted_title: "Removed!",
    applications_deleted_msg: "Application deleted.",
    applications_status_updated_title: "Status updated!",
    applications_status_updated_msg: (status: string) => `It is now ${status}.`,
    applications_error_fetch: "Error fetching applications",
    applications_error_create: "Error creating",
    applications_error_edit: "Error editing",
    applications_error_update_status: "Error updating status",
    applications_error_delete: "Error deleting",
    applications_error_retry: "Please try again.",
    applications_error_api_hint:
      "Make sure the API is running on localhost:8080 and CORS is enabled for localhost:5173.",
    // New fields (Sprint 2)
    notes: "Notes",
    notes_placeholder: "Notes, next steps, contacts...",
    job_url: "Job URL",
    job_url_placeholder: "https://linkedin.com/jobs/...",
    salary: "Salary / Range",
    salary_placeholder: "Ex: $80k–100k",
    open_job_link: "Open job link",
  },
} as const;

export type Translations = (typeof translations)["pt"];

export function useTranslation(): Translations {
  const { profile } = useUser();
  return translations[profile.language] as unknown as Translations;
}
